[package]
name = "simple-config-loader"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "*"
strum = { version = "*", features = ["derive"] }
config = "*"
anyhow = "*"
dotenvy = "*"
simple-encrypt = { path = "../simple-encrypt" }